name: Build All Actions

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.7.0'

      - name: Npm Build
        id: npm-build
        run: |
          npm install
          npm run build
          VERSION=$(node -p "require('./package.json').version")
          echo "Built version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"


      - name: Tag Actions
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=${{ steps.npm-build.outputs.version }}
          git tag new-tag
          git push origin new-tag
          echo "Tagging with version $VERSION"
          git tag $VERSION
          git push origin $VERSION
